language: node_js
node_js:
- 0.8

before_script:
- mysql -e 'create database appdevtest;'
- echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

- cd server
- npm install
- cd ..

script: 
- ./server/node_modules/mocha/bin/mocha -t 10000 -R spec
